name:  ProgressBar
author:  [davidwalsh,mcfedr]
current:  1.2
category:  Interface
tags:  [progress,fx,forms,images]
docs:  https://github.com/mcfedr/ProgressBar
demo:  http://davidwalsh.name/js/progressbar
